AllCops:
  TargetRubyVersion: 2.6

Metrics/MethodLength:
  Max: 30

Layout/LineLength:
  Max: 100

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/AbcSize:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 8
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/BlockLength:
  Max: 35
  Exclude:
    - '*.gemspec'
    - Rakefile
    - 'spec/**/*_spec.rb'
    - 'spec/spec_helper.rb'

Security/Eval:
  Exclude:
    - Gemfile
